138 handling-dashboard-firstpage
Northeastern-Electric-Racing/Argos pull request #153
Opened 2024-04-14 21:25 UTC by leoleader

havent done anything yet just making draft pr

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #138

2024-04-20 20:49 UTC, Peyton-McKee requested changes
This looks great. Can you just add some mock data to the backend to test it as well

2024-04-20 20:49 UTC, Peyton-McKee commented on angular-client/src/components/handling-graphs/gas-brake-pos/gas-brake-pos.component.ts
> +  // {name: blah, data = data}[] and then act accordingly based off given type.
yeah that would mean you could graph multiple lines on a graph

2024-04-20 20:49 UTC, Peyton-McKee commented on angular-client/src/components/handling-graphs/long-vs-lat/long-vs-lat.component.html
> +<info-graph [data]="data" graphContainerId="longVsLatGraph" title="Longitude vs Latitude Acceleration" color="primary">
longvslat wont work as a line graph, https://apexcharts.com/javascript-chart-demos/radar-charts/ try using this kind of graph

2024-04-20 20:49 UTC, Peyton-McKee commented on angular-client/src/components/handling-graphs/steerPos-vs-time/steerPos-vs-time.component.ts
> +      this.data.push({ x: new Date().getTime(), y: parseInt(value.values[0]) });
use the tiemstamp from the value,

2024-04-20 20:49 UTC, Peyton-McKee commented on angular-client/src/components/handling-graphs/shot-vs-time/shot-vs-time.component.ts
> +      this.data.push({ x: new Date().getTime(), y: parseInt(value.values[0]) });
use timestamp from the value

2024-04-20 20:49 UTC, Peyton-McKee commented on angular-client/src/components/handling-graphs/ride-height-time/ride-height-time.component.ts
> +      this.data.push({ x: new Date().getTime(), y: parseInt(value.values[0]) });
use timestamp from the value

2024-05-18 06:02 UTC, jr1221 commented
Brake pedal topic: `Pedals-Brake_1` (range 0 to ~800 ish)
Accel pedal topoc: `Pedals-Accelerator_1` (range ~1000 to ~4500 ish)

There is `_2` for both, but idk if you need to read both sensors.

2024-09-19 00:57 UTC, closed without merging

2024-09-19 00:58 UTC, RChandler234 commented
Stale asf