Scylla Server in Rust
Northeastern-Electric-Racing/Argos pull request #171
Opened 2024-07-23 22:36 UTC by jr1221

This adds a whole lot.

The new folder scylla-server-rust contains a complete scylla implementation in rust.  Functional differences to the JS one:
- Implements a `Latency` key to see latency to server
- Implements a POST `runs/new` endpoint for creating a new run
- Adds logging via env vars (see README)
- Changes names, types and defaults of some other setting env vars (see bottom of README)

Stuff outside of the `scylla-server-rust` scope:
- Add docker compose profile logic to apply various system configurations quickly
- github workflows to build `argos-client` and `argos-scylla` seperately
- Root README updates for all of the above.

2024-08-29 23:25 UTC, Peyton-McKee commented on scylla-server-rust/src/services/data_service.rs
> +
comments?????

2024-08-29 23:26 UTC, Peyton-McKee approved these changes, later dismissed
YIPPPEEEE

2024-09-16 03:15 UTC, RChandler234 requested changes

2024-09-16 03:15 UTC, RChandler234 commented on compose.yml
> +  scylla-server-rust:
I know this is an annoying ask, but if we're making this the main one, can you rename it to scylla-server and the other one to scylla-server-typescript.

2024-09-16 03:15 UTC, RChandler234 commented on compose.yml
> +  scylla-server-rust:
After this is merged, I want to try forking the repo soon to make Argos 2.0, and not include the IOS code/ old typescript code in it since we won't be supporting those going forward. I think it's messy to have it all just sitting in this repo

2024-09-16 03:15 UTC, RChandler234 commented on scylla-server-rust/src/controllers/data_controller.rs
> +pub async fn get_data(
all the controller methods should have a lil one line comment

2024-09-16 03:15 UTC, RChandler234 commented on scylla-server-rust/src/main.rs
> +        // DATA TYPE ROUTES
nitpick: all of them should say ROUTES or none of them should

2024-09-16 03:15 UTC, RChandler234 commented on scylla-server-rust/integration_test.sh
> +echo "Please stop your db in docker"
lol, is the only way to just have them manually stop it once the tests are done?

2024-09-16 23:53 UTC, merged