build(webapp/deps): migrate to Angular v18
Northeastern-Electric-Racing/Argos pull request #185
Opened 2024-09-13 02:53 UTC by Char2sGu

2024-09-13 02:57 UTC, Char2sGu commented on angular-client/src/index.html
> +    <app-context></app-context>
Custom Elements are not allowed to be self-closed. `<app-context />` was an invalid syntax, and after migration, this causes the build to fail

2024-09-13 02:57 UTC, Char2sGu commented on angular-client/src/app/app.module.ts
> +  constructor (
This formatting issue will be addressed later by forcing formatting and linting in Git Hooks

2024-09-13 02:57 UTC, Char2sGu commented on angular-client/src/app/app.module.ts
> +    provideHttpClient(withInterceptorsFromDi())
Angular is going "standalone". The `HttpClientModule` is deprecated and replaced by the standalone provider factory `provideHttpClient`

2024-09-13 02:57 UTC, Char2sGu commented on angular-client/src/app/app.module.ts
> +    provideHttpClient(withInterceptorsFromDi())
The new http interceptor api uses functional interceptors. In order to enable class-based interceptors, `withInterceptorsFromDi` is necessary.

2024-09-16 05:10 UTC, RChandler234 requested changes
This fucked with the sidebar design a bit somehow. I honestly like the new one better, but could you make it so the item highlight doesn't overflow on the right side
New:
![image](https://github.com/user-attachments/assets/4055c7c6-03d2-4a4b-89c8-bdf8f563b087)
Old:
![image](https://github.com/user-attachments/assets/1ed35c18-7a7d-4007-8205-d32d2c343da4)

2024-09-16 17:19 UTC, Char2sGu commented
Sure. Since we bumped the version of Angular Material and PrimeNG, some updates in these packages might result in unexpected behaviors. I’ll look into that today.

2024-09-17 00:25 UTC, Char2sGu commented
![image](https://github.com/user-attachments/assets/c367fc98-2eb3-4f6c-8584-234771244c9f)

2024-09-17 04:42 UTC, RChandler234 approved these changes
LGTM 🔥

2024-09-17 04:42 UTC, merged