#209 allow for arrowing through graph screen values/tabs
Northeastern-Electric-Racing/Argos pull request #217
Opened 2024-09-29 16:33 UTC by SomShrivastava

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-10-07 17:08 UTC, somshrivastava commented
When arrowing through the tabs, if you are on the first data type of any node, it won't show it as selected... not sure why yet, still trying to fix it.

2024-10-25 13:48 UTC, RChandler234 requested changes

2024-10-25 13:48 UTC, RChandler234 commented on angular-client/src/pages/graph-page/graph-page.component.ts
> +      console.log(dataType);
remove

2024-10-25 13:48 UTC, RChandler234 commented on angular-client/src/pages/graph-page/graph-sidebar/sidebar-card/sidebar-card.component.ts
> +    // const card = document.getElementById(this.title);
remove any unused code

2024-10-28 04:47 UTC, closed without merging