Diesel Performance Fixes, Batching Improvements, New Allocator
Northeastern-Electric-Racing/Argos pull request #262
Opened 2024-12-21 20:59 UTC by jr1221

## Changes

- Switch to diesel-async, to better use the tokio runtime to organize threads
Rationale:  Performance of blocking threads decreases with more threads in use, affecting large chunk batching and the #243 code
- Switch to jemalloc, as extreme memory use was being observed with #243 
Rationale: The system allocator was not freeing the memory used by the batching tasks effectively, resulting in excessive memory usage.  It takes now approximately 1-2gb of RAM to upload an hour of data, and that RAM is released back when the upload is complete.  Previously it was 5-10gb, and the memory was not freed.
- Modify the values field of the DATA table to be NOT NULL, modify the values field to be REAL instead of DOUBLE. PRECISION.
Rationale (found in the docs for DataInsert): This aligns closer to the actual data we recieve, which is not null 4 byte floating point integers.  This allows less re-allocation of data when converting our recieved protobuf to the data the database is looking for, improving performance.
- Redo chunking logic. 
Rationale:  Before, chunks of data to upload were split into a few even chunks and one chunk of only a few points.  The new algorithm better evens out the chunks.  It still could use improvement, and more investigation into the libpq instruction limit could be warrented.

## Notes

Jemalloc may fail to build on aarch64, hence the CI running, so we should pay attention to any unsoundness or stability issues.

## Test Cases

- All functionality normal, perhaps a little faster.
## To Do

_Any remaining things that need to get done_

- [ ] Ensure CI works

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #244
Closes #184

2025-01-06 05:00 UTC, bracyw commented on scylla-server/src/db_handler.rs
> +    datatype_list: FxHashSet<String>,
Why the switch to FxHashSet

2025-01-06 05:05 UTC, bracyw commented on scylla-server/src/db_handler.rs
> +                    let chunk_size = msg_len / ((msg_len / 8190) + 1);
Why are you now dividing by 8190 instead of 16380, something special about dividing max params by 8 instead of 4?

2025-01-06 05:08 UTC, bracyw commented on scylla-server/src/db_handler.rs
> +        // the match batch size to reasonably expect
* the max

2025-01-06 05:09 UTC, bracyw commented on scylla-server/src/db_handler.rs
> +                        // mem::take allows us to assign the value of data queue vec::new() while maintaining the memory for data_channel ownership
where is mem::take ?

2025-01-06 05:33 UTC, bracyw commented on scylla-server/src/db_handler.rs
>                      // libpq has max 65535 params, therefore batch
I actually never understood this fully. why is the batching logic needed for diesel... is it because it let's you try and insert more data then libpq can handle. Does prisma just manage this itself?

2025-01-06 05:37 UTC, bracyw requested changes
Integration tests fail sometimes when you either have the database disabled in docker or haven't set it up yet. I think just adding a sleep like your github tests. For now we can probably just restart or remove the database if it is already a docker container but disabled.... I can push changes for this if you want.

2025-01-06 12:32 UTC, jr1221 commented
Ya can unadd the fix to integration tests?  Thanks.

2025-01-06 12:38 UTC, jr1221 commented on scylla-server/src/db_handler.rs
> +    datatype_list: FxHashSet<String>,
1. A hashset should be used whenever you are checking for uniqueness rather than storing possibly duplicate items.
2. Rust has multiple hashing algos builtin, the default is slow but secure, since we don't need security we can switch to a faster one.  This library fxhash is just a syntactic sugar for switching the hashing algorithm. For example the official rust compiler uses fxhash instead of the default.  It is considerably faster and considered best practice.  I measured about .25% speed time reduction in the overall time usage hashing in the whole program when I switched, which is considerable.

2025-01-06 12:39 UTC, jr1221 commented on scylla-server/src/db_handler.rs
> +                    let chunk_size = msg_len / ((msg_len / 8190) + 1);
Oh ya forgot to investigate that.  The switch to diesel async doubled the number of instructions per insert.  I'll do some investigating there. It's a very annoying limit.

2025-01-06 12:40 UTC, jr1221 commented on scylla-server/src/db_handler.rs
> +                        // mem::take allows us to assign the value of data queue vec::new() while maintaining the memory for data_channel ownership
Oops will remove.  Mem take is pretty cool tho, but turns out I didn't need it.

2025-01-06 12:41 UTC, jr1221 commented on scylla-server/src/db_handler.rs
>                      // libpq has max 65535 params, therefore batch
I guess prisma splits the queries as needed.  I doubt they work around libpq as it's kinda the best way to communicate with postgres.  It's a very annoying limit but kinda inherent to postgres.

2025-01-07 03:09 UTC, bracyw approved these changes
LGTM

2025-01-07 03:13 UTC, merged